on: push
name: build
jobs:
  build:
    name: copy to gcs
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: './cloud_functions'
        destination: 'pcf-portfolio-cloud-functions-code'